const animeData = [
    {
        id: 1,
        title: 'Ангел по соседству',
        rating: 8.5,
        year: 2023,
        episodes: 12,
        imagePath: 'AnimeImagePath/OIP (1).jpg',
        voice: 'Anilibria',
        episodeList: [
            {number: 1, url: 'https://kodikplayer.com/seria/1090328/a60078e04157973fe4200023aabece02/720p'},
            {number: 2, url: 'https://anilibria.top/anime/video/episode/e4d1b6c7-b80b-431b-996f-91f5ff653c1f'},
        ],
    },
    {
        id: 2,
        title: 'Благоухающий цветок расцветает с достоинством',
        rating: 8.6,
        year: 2025,
        episodes: 12,
        imagePath: 'AnimeImagePath/kaoruHanaWa.jpg',
        voice: 'Anilibria',
        episodeList: [],
    },
    {
        id: 3,
        title: 'Атака Титанов',
        rating: 9.3,
        year: 2013,
        episodes: 87,
        imagePath: 'AnimeImagePath/attackOnTitan.jpg',
        voice: 'Anilibria',
        episodeList: [],
    },
];